In [1]:
import os
import sys
import pandas as pd

In [2]:
sys.path.append(r'D:\OneDrive\Programming\documents_python\NUS Courses\DBA5106\Course-DBA5106\group_project\gp3')
from utils.logger import logger
from utils.config import RAW_DATA_DIR, PROCESSED_DATA_DIR, FIGURE_DIR
from utils.data_porter import save_to_csv, read_from_csv

In [3]:
user_tweets_feature_engineer = read_from_csv('user_tweets_final_numeric.csv', PROCESSED_DATA_DIR)

# Feature Engineer

In [4]:
user_tweets_feature_engineer.head()

,followers_count,following_count,tweets_count,tweets_content,state_back,tweet_tokenized,tweet_tokenized_stem,tweet_tokenized_lemma,tweet_tokenized_filtered,tweet_clean,...,wow,write,wrong,ya,yay,ye,yeah,year,yesterday,yet
0,379.0,383.0,45.0,"rt @amelia12610461: #february5, the cuban cycl...",1,"['rt', 'the', 'cuban', 'cyclist', 'arlenis', '...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'cuban', 'cyclist', 'arleni', 'sierra',...",rt cuban cyclist arleni sierra first place fir...,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.049154,0.000000,0.060629
1,224.0,253.0,6.0,@diazcanelb celia sánchez occupies a significa...,1,"['celia', 'sánchez', 'occupies', 'a', 'signifi...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'signific', 'pl...",celia sánchez occupi signific place histori cu...,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
2,535.0,1144.0,9048.0,@soniagupta504 don`t worry everithing will be ...,1,"['don', 't', 'worry', 'everithing', 'will', 'b...","['don', 't', 'worri', 'everith', 'will', 'be',...","['don', 't', 'worri', 'everith', 'will', 'be',...","['worri', 'everith', 'ok', 'vscode', 'best', '...",worri everith ok vscode best editor ani backen...,...,0.006021,0.04738,0.002811,0.000541,0.002049,0.008471,0.00279,0.043911,0.012778,0.011926
3,827.0,740.0,165.0,rt @diazcanelb: state terrorism openly declare...,1,"['rt', 'state', 'terrorism', 'openly', 'declar...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...",rt state terror openli declar venezuela defeat...,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.151733,0.025067,0.023394
4,43.0,304.0,1.0,rt @diazcanelb: patient ill with covid-19: pre...,1,"['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'covid', 'precaut', '...",rt patient ill covid precaut must heighten peo...,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000

In [5]:
user_tweets_feature_engineer['count_word'] = user_tweets_feature_engineer.apply(
    lambda row: len(row['tweet_tokenized']), axis=1)

In [6]:
def count_symbol(word_tokens, symbol):
    return word_tokens.count(symbol)

# user_tweets_feature_engineer['count_reweet'] = user_tweets_feature_engineer.apply(
#     lambda row: count_symbol(row['tweets_content'], 'rt'), axis=1)
# user_tweets_feature_engineer['count_mention'] = user_tweets_feature_engineer.apply(
#     lambda row: count_symbol(row['tweets_content'], '@'), axis=1)
# user_tweets_feature_engineer['count_hashtag'] = user_tweets_feature_engineer.apply(
#     lambda row: count_symbol(row['tweets_content'], '#'), axis=1)
# user_tweets_feature_engineer['count_url'] = user_tweets_feature_engineer.apply(
#     lambda row: count_symbol(row['tweets_content'], 'http'), axis=1)
user_tweets_feature_engineer['count_sentence'] = user_tweets_feature_engineer.apply(
    lambda row: count_symbol(row['tweets_content'], '.'), axis=1)

In [7]:
user_tweets_feature_engineer

,followers_count,following_count,tweets_count,tweets_content,state_back,tweet_tokenized,tweet_tokenized_stem,tweet_tokenized_lemma,tweet_tokenized_filtered,tweet_clean,...,wrong,ya,yay,ye,yeah,year,yesterday,yet,count_word,count_sentence
0,379.0,383.0,45.0,"rt @amelia12610461: #february5, the cuban cycl...",1,"['rt', 'the', 'cuban', 'cyclist', 'arlenis', '...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'cuban', 'cyclist', 'arleni', 'sierra',...",rt cuban cyclist arleni sierra first place fir...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.049154,0.000000,0.060629,6867,40
1,224.0,253.0,6.0,@diazcanelb celia sánchez occupies a significa...,1,"['celia', 'sánchez', 'occupies', 'a', 'signifi...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'signific', 'pl...",celia sánchez occupi signific place histori cu...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1118,4
2,535.0,1144.0,9048.0,@soniagupta504 don`t worry everithing will be ...,1,"['don', 't', 'worry', 'everithing', 'will', 'b...","['don', 't', 'worri', 'everith', 'will', 'be',...","['don', 't', 'worri', 'everith', 'will', 'be',...","['worri', 'everith', 'ok', 'vscode', 'best', '...",worri everith ok vscode best editor ani backen...,...,0.002811,0.000541,0.002049,0.008471,0.002790,0.043911,0.012778,0.011926,986626,10162
3,827.0,740.0,165.0,rt @diazcanelb: state terrorism openly declare...,1,"['rt', 'state', 'terrorism', 'openly', 'declar...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...",rt state terror openli declar venezuela defeat...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.151733,0.025067,0.023394,23609,193
4,43.0,304.0,1.0,rt @diazcanelb: patient ill with covid-19: pre...,1,"['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'covid', 'precaut', '...",rt patient ill covid precaut must heighten peo...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106592,5.0,16.0,10.0,just checked into the @rogersmithhotel -- che...,0,"['just', 'checked', 'into', 'the', 'checkin', ...","['just', 'check', 'into', 'the', 'checkin', 'b...","['just', 'check', 'into', 'the', 'checkin', 'b...","['check', 'checkin', 'hope', 'get', 'room', 'e...",check checkin hope get room earli need sleep m...,...,0.000000,0.056265,0.053328,0.000000,0.096813,0.000000,0.055420,0.103444,1116,16
106593,43.0,38.0,343.0,"swap meet was fun today, summer time! even tho...",0,"['swap', 'meet', 'was', 'fun', 'today', 'summe...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...",swap meet wa fun today summer time even though...,...,0.000000,0.110673,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32545,415
106594,4.0,84.0,51.0,@audio_rush oh wells. i can complain all i wan...,0,"['oh', 'wells', 'i', 'can', 'complain', 'all',...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'complain', 'want', 'aboutt', '...",oh well complain want aboutt school want alrea...,...,0.101721,0.097803,0.000000,0.000000,0.000000,0.000000,0.096335,0.089906,4667,79
106595,0.0,14.0,2.0,i ate too many carrots trying to knockout thi...,0,"['i', 'ate', 'too', 'many', 'carrots', 'trying...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['ate', 'mani', 'carrot', 'tri', 'knockout', '...",ate mani carrot tri knockout thi last paper fa...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,179,0
106596,2.0,24.0,10.0,off to the gym shortly never quite made the 5...,0,"['off', 'to', 'the', 'gym', 'shortly', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['gym', 'shortli', 'never', 'quit', 'made', 'm...",gym shortli never quit made mile today mile wo...,...,0.000000,0.404206,0.000000,0.000000,0.347752,0.000000,0.000000,0.000000,1003,15

In [8]:
# user_tweets_feature_engineer['reweet_per_word'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_reweet'] / (row['count_word'] + 1), axis=1)
# user_tweets_feature_engineer['mention_per_word'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_mention'] / (row['count_word'] + 1), axis=1)
# user_tweets_feature_engineer['hashtag_per_word'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_hashtag'] / (row['count_word'] + 1), axis=1)
# user_tweets_feature_engineer['url_per_word'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_url'] / (row['count_word'] + 1), axis=1)

In [9]:
user_tweets_feature_engineer

,followers_count,following_count,tweets_count,tweets_content,state_back,tweet_tokenized,tweet_tokenized_stem,tweet_tokenized_lemma,tweet_tokenized_filtered,tweet_clean,...,wrong,ya,yay,ye,yeah,year,yesterday,yet,count_word,count_sentence
0,379.0,383.0,45.0,"rt @amelia12610461: #february5, the cuban cycl...",1,"['rt', 'the', 'cuban', 'cyclist', 'arlenis', '...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'cuban', 'cyclist', 'arleni', 'sierra',...",rt cuban cyclist arleni sierra first place fir...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.049154,0.000000,0.060629,6867,40
1,224.0,253.0,6.0,@diazcanelb celia sánchez occupies a significa...,1,"['celia', 'sánchez', 'occupies', 'a', 'signifi...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'signific', 'pl...",celia sánchez occupi signific place histori cu...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1118,4
2,535.0,1144.0,9048.0,@soniagupta504 don`t worry everithing will be ...,1,"['don', 't', 'worry', 'everithing', 'will', 'b...","['don', 't', 'worri', 'everith', 'will', 'be',...","['don', 't', 'worri', 'everith', 'will', 'be',...","['worri', 'everith', 'ok', 'vscode', 'best', '...",worri everith ok vscode best editor ani backen...,...,0.002811,0.000541,0.002049,0.008471,0.002790,0.043911,0.012778,0.011926,986626,10162
3,827.0,740.0,165.0,rt @diazcanelb: state terrorism openly declare...,1,"['rt', 'state', 'terrorism', 'openly', 'declar...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...",rt state terror openli declar venezuela defeat...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.151733,0.025067,0.023394,23609,193
4,43.0,304.0,1.0,rt @diazcanelb: patient ill with covid-19: pre...,1,"['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'covid', 'precaut', '...",rt patient ill covid precaut must heighten peo...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106592,5.0,16.0,10.0,just checked into the @rogersmithhotel -- che...,0,"['just', 'checked', 'into', 'the', 'checkin', ...","['just', 'check', 'into', 'the', 'checkin', 'b...","['just', 'check', 'into', 'the', 'checkin', 'b...","['check', 'checkin', 'hope', 'get', 'room', 'e...",check checkin hope get room earli need sleep m...,...,0.000000,0.056265,0.053328,0.000000,0.096813,0.000000,0.055420,0.103444,1116,16
106593,43.0,38.0,343.0,"swap meet was fun today, summer time! even tho...",0,"['swap', 'meet', 'was', 'fun', 'today', 'summe...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...",swap meet wa fun today summer time even though...,...,0.000000,0.110673,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32545,415
106594,4.0,84.0,51.0,@audio_rush oh wells. i can complain all i wan...,0,"['oh', 'wells', 'i', 'can', 'complain', 'all',...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'complain', 'want', 'aboutt', '...",oh well complain want aboutt school want alrea...,...,0.101721,0.097803,0.000000,0.000000,0.000000,0.000000,0.096335,0.089906,4667,79
106595,0.0,14.0,2.0,i ate too many carrots trying to knockout thi...,0,"['i', 'ate', 'too', 'many', 'carrots', 'trying...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['ate', 'mani', 'carrot', 'tri', 'knockout', '...",ate mani carrot tri knockout thi last paper fa...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,179,0
106596,2.0,24.0,10.0,off to the gym shortly never quite made the 5...,0,"['off', 'to', 'the', 'gym', 'shortly', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['gym', 'shortli', 'never', 'quit', 'made', 'm...",gym shortli never quit made mile today mile wo...,...,0.000000,0.404206,0.000000,0.000000,0.347752,0.000000,0.000000,0.000000,1003,15

In [10]:
# user_tweets_feature_engineer['reweet_per_sentence'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_reweet'] / (row['count_sentence'] + 1), axis=1)
# user_tweets_feature_engineer['mention_per_sentence'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_mention'] / (row['count_sentence'] + 1), axis=1)
# user_tweets_feature_engineer['hashtag_per_sentence'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_hashtag'] / (row['count_sentence'] + 1), axis=1)
# user_tweets_feature_engineer['url_per_sentence'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_url'] / (row['count_sentence'] + 1), axis=1)

In [11]:
user_tweets_feature_engineer

,followers_count,following_count,tweets_count,tweets_content,state_back,tweet_tokenized,tweet_tokenized_stem,tweet_tokenized_lemma,tweet_tokenized_filtered,tweet_clean,...,wrong,ya,yay,ye,yeah,year,yesterday,yet,count_word,count_sentence
0,379.0,383.0,45.0,"rt @amelia12610461: #february5, the cuban cycl...",1,"['rt', 'the', 'cuban', 'cyclist', 'arlenis', '...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'cuban', 'cyclist', 'arleni', 'sierra',...",rt cuban cyclist arleni sierra first place fir...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.049154,0.000000,0.060629,6867,40
1,224.0,253.0,6.0,@diazcanelb celia sánchez occupies a significa...,1,"['celia', 'sánchez', 'occupies', 'a', 'signifi...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'signific', 'pl...",celia sánchez occupi signific place histori cu...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1118,4
2,535.0,1144.0,9048.0,@soniagupta504 don`t worry everithing will be ...,1,"['don', 't', 'worry', 'everithing', 'will', 'b...","['don', 't', 'worri', 'everith', 'will', 'be',...","['don', 't', 'worri', 'everith', 'will', 'be',...","['worri', 'everith', 'ok', 'vscode', 'best', '...",worri everith ok vscode best editor ani backen...,...,0.002811,0.000541,0.002049,0.008471,0.002790,0.043911,0.012778,0.011926,986626,10162
3,827.0,740.0,165.0,rt @diazcanelb: state terrorism openly declare...,1,"['rt', 'state', 'terrorism', 'openly', 'declar...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...",rt state terror openli declar venezuela defeat...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.151733,0.025067,0.023394,23609,193
4,43.0,304.0,1.0,rt @diazcanelb: patient ill with covid-19: pre...,1,"['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'covid', 'precaut', '...",rt patient ill covid precaut must heighten peo...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106592,5.0,16.0,10.0,just checked into the @rogersmithhotel -- che...,0,"['just', 'checked', 'into', 'the', 'checkin', ...","['just', 'check', 'into', 'the', 'checkin', 'b...","['just', 'check', 'into', 'the', 'checkin', 'b...","['check', 'checkin', 'hope', 'get', 'room', 'e...",check checkin hope get room earli need sleep m...,...,0.000000,0.056265,0.053328,0.000000,0.096813,0.000000,0.055420,0.103444,1116,16
106593,43.0,38.0,343.0,"swap meet was fun today, summer time! even tho...",0,"['swap', 'meet', 'was', 'fun', 'today', 'summe...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...",swap meet wa fun today summer time even though...,...,0.000000,0.110673,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32545,415
106594,4.0,84.0,51.0,@audio_rush oh wells. i can complain all i wan...,0,"['oh', 'wells', 'i', 'can', 'complain', 'all',...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'complain', 'want', 'aboutt', '...",oh well complain want aboutt school want alrea...,...,0.101721,0.097803,0.000000,0.000000,0.000000,0.000000,0.096335,0.089906,4667,79
106595,0.0,14.0,2.0,i ate too many carrots trying to knockout thi...,0,"['i', 'ate', 'too', 'many', 'carrots', 'trying...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['ate', 'mani', 'carrot', 'tri', 'knockout', '...",ate mani carrot tri knockout thi last paper fa...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,179,0
106596,2.0,24.0,10.0,off to the gym shortly never quite made the 5...,0,"['off', 'to', 'the', 'gym', 'shortly', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['gym', 'shortli', 'never', 'quit', 'made', 'm...",gym shortli never quit made mile today mile wo...,...,0.000000,0.404206,0.000000,0.000000,0.347752,0.000000,0.000000,0.000000,1003,15

In [12]:
# user_tweets_feature_engineer['reweet_per_tweet'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_reweet'] / (row['tweets_count'] + 1), axis=1)
# user_tweets_feature_engineer['mention_per_tweet'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_mention'] / (row['tweets_count'] + 1), axis=1)
# user_tweets_feature_engineer['hashtag_per_tweet'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_hashtag'] / (row['tweets_count'] + 1), axis=1)
# user_tweets_feature_engineer['url_per_tweet'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_url'] / (row['tweets_count'] + 1), axis=1)

In [13]:
user_tweets_feature_engineer

,followers_count,following_count,tweets_count,tweets_content,state_back,tweet_tokenized,tweet_tokenized_stem,tweet_tokenized_lemma,tweet_tokenized_filtered,tweet_clean,...,wrong,ya,yay,ye,yeah,year,yesterday,yet,count_word,count_sentence
0,379.0,383.0,45.0,"rt @amelia12610461: #february5, the cuban cycl...",1,"['rt', 'the', 'cuban', 'cyclist', 'arlenis', '...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'cuban', 'cyclist', 'arleni', 'sierra',...",rt cuban cyclist arleni sierra first place fir...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.049154,0.000000,0.060629,6867,40
1,224.0,253.0,6.0,@diazcanelb celia sánchez occupies a significa...,1,"['celia', 'sánchez', 'occupies', 'a', 'signifi...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'signific', 'pl...",celia sánchez occupi signific place histori cu...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1118,4
2,535.0,1144.0,9048.0,@soniagupta504 don`t worry everithing will be ...,1,"['don', 't', 'worry', 'everithing', 'will', 'b...","['don', 't', 'worri', 'everith', 'will', 'be',...","['don', 't', 'worri', 'everith', 'will', 'be',...","['worri', 'everith', 'ok', 'vscode', 'best', '...",worri everith ok vscode best editor ani backen...,...,0.002811,0.000541,0.002049,0.008471,0.002790,0.043911,0.012778,0.011926,986626,10162
3,827.0,740.0,165.0,rt @diazcanelb: state terrorism openly declare...,1,"['rt', 'state', 'terrorism', 'openly', 'declar...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...",rt state terror openli declar venezuela defeat...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.151733,0.025067,0.023394,23609,193
4,43.0,304.0,1.0,rt @diazcanelb: patient ill with covid-19: pre...,1,"['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'covid', 'precaut', '...",rt patient ill covid precaut must heighten peo...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106592,5.0,16.0,10.0,just checked into the @rogersmithhotel -- che...,0,"['just', 'checked', 'into', 'the', 'checkin', ...","['just', 'check', 'into', 'the', 'checkin', 'b...","['just', 'check', 'into', 'the', 'checkin', 'b...","['check', 'checkin', 'hope', 'get', 'room', 'e...",check checkin hope get room earli need sleep m...,...,0.000000,0.056265,0.053328,0.000000,0.096813,0.000000,0.055420,0.103444,1116,16
106593,43.0,38.0,343.0,"swap meet was fun today, summer time! even tho...",0,"['swap', 'meet', 'was', 'fun', 'today', 'summe...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...",swap meet wa fun today summer time even though...,...,0.000000,0.110673,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32545,415
106594,4.0,84.0,51.0,@audio_rush oh wells. i can complain all i wan...,0,"['oh', 'wells', 'i', 'can', 'complain', 'all',...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'complain', 'want', 'aboutt', '...",oh well complain want aboutt school want alrea...,...,0.101721,0.097803,0.000000,0.000000,0.000000,0.000000,0.096335,0.089906,4667,79
106595,0.0,14.0,2.0,i ate too many carrots trying to knockout thi...,0,"['i', 'ate', 'too', 'many', 'carrots', 'trying...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['ate', 'mani', 'carrot', 'tri', 'knockout', '...",ate mani carrot tri knockout thi last paper fa...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,179,0
106596,2.0,24.0,10.0,off to the gym shortly never quite made the 5...,0,"['off', 'to', 'the', 'gym', 'shortly', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['gym', 'shortli', 'never', 'quit', 'made', 'm...",gym shortli never quit made mile today mile wo...,...,0.000000,0.404206,0.000000,0.000000,0.347752,0.000000,0.000000,0.000000,1003,15

In [14]:
user_tweets_feature_engineer['word_per_sentence'] = user_tweets_feature_engineer.apply(
    lambda row: row['count_word'] / (row['count_sentence'] + 1), axis=1)
# user_tweets_feature_engineer['word_per_tweet'] = user_tweets_feature_engineer.apply(
#     lambda row: row['count_word'] / (row['tweets_count'] + 1), axis=1)
user_tweets_feature_engineer['sentence_per_tweet'] = user_tweets_feature_engineer.apply(
    lambda row: row['count_sentence'] / (row['tweets_count'] + 1), axis=1)

In [15]:
user_tweets_feature_engineer

,followers_count,following_count,tweets_count,tweets_content,state_back,tweet_tokenized,tweet_tokenized_stem,tweet_tokenized_lemma,tweet_tokenized_filtered,tweet_clean,...,yay,ye,yeah,year,yesterday,yet,count_word,count_sentence,word_per_sentence,sentence_per_tweet
0,379.0,383.0,45.0,"rt @amelia12610461: #february5, the cuban cycl...",1,"['rt', 'the', 'cuban', 'cyclist', 'arlenis', '...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'the', 'cuban', 'cyclist', 'arleni', 's...","['rt', 'cuban', 'cyclist', 'arleni', 'sierra',...",rt cuban cyclist arleni sierra first place fir...,...,0.000000,0.000000,0.000000,0.049154,0.000000,0.060629,6867,40,167.487805,0.869565
1,224.0,253.0,6.0,@diazcanelb celia sánchez occupies a significa...,1,"['celia', 'sánchez', 'occupies', 'a', 'signifi...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'a', 'signific'...","['celia', 'sánchez', 'occupi', 'signific', 'pl...",celia sánchez occupi signific place histori cu...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1118,4,223.600000,0.571429
2,535.0,1144.0,9048.0,@soniagupta504 don`t worry everithing will be ...,1,"['don', 't', 'worry', 'everithing', 'will', 'b...","['don', 't', 'worri', 'everith', 'will', 'be',...","['don', 't', 'worri', 'everith', 'will', 'be',...","['worri', 'everith', 'ok', 'vscode', 'best', '...",worri everith ok vscode best editor ani backen...,...,0.002049,0.008471,0.002790,0.043911,0.012778,0.011926,986626,10162,97.080193,1.122997
3,827.0,740.0,165.0,rt @diazcanelb: state terrorism openly declare...,1,"['rt', 'state', 'terrorism', 'openly', 'declar...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...","['rt', 'state', 'terror', 'openli', 'declar', ...",rt state terror openli declar venezuela defeat...,...,0.000000,0.000000,0.000000,0.151733,0.025067,0.023394,23609,193,121.695876,1.162651
4,43.0,304.0,1.0,rt @diazcanelb: patient ill with covid-19: pre...,1,"['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'with', 'covid', 'pre...","['rt', 'patient', 'ill', 'covid', 'precaut', '...",rt patient ill covid precaut must heighten peo...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129,2,43.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106592,5.0,16.0,10.0,just checked into the @rogersmithhotel -- che...,0,"['just', 'checked', 'into', 'the', 'checkin', ...","['just', 'check', 'into', 'the', 'checkin', 'b...","['just', 'check', 'into', 'the', 'checkin', 'b...","['check', 'checkin', 'hope', 'get', 'room', 'e...",check checkin hope get room earli need sleep m...,...,0.053328,0.000000,0.096813,0.000000,0.055420,0.103444,1116,16,65.647059,1.454545
106593,43.0,38.0,343.0,"swap meet was fun today, summer time! even tho...",0,"['swap', 'meet', 'was', 'fun', 'today', 'summe...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...","['swap', 'meet', 'wa', 'fun', 'today', 'summer...",swap meet wa fun today summer time even though...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32545,415,78.233173,1.206395
106594,4.0,84.0,51.0,@audio_rush oh wells. i can complain all i wan...,0,"['oh', 'wells', 'i', 'can', 'complain', 'all',...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'i', 'can', 'complain', 'all', ...","['oh', 'well', 'complain', 'want', 'aboutt', '...",oh well complain want aboutt school want alrea...,...,0.000000,0.000000,0.000000,0.000000,0.096335,0.089906,4667,79,58.337500,1.519231
106595,0.0,14.0,2.0,i ate too many carrots trying to knockout thi...,0,"['i', 'ate', 'too', 'many', 'carrots', 'trying...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['i', 'ate', 'too', 'mani', 'carrot', 'tri', '...","['ate', 'mani', 'carrot', 'tri', 'knockout', '...",ate mani carrot tri knockout thi last paper fa...,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,179,0,179.000000,0.000000
106596,2.0,24.0,10.0,off to the gym shortly never quite made the 5...,0,"['off', 'to', 'the', 'gym', 'shortly', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['off', 'to', 'the', 'gym', 'shortli', 'never'...","['gym', 'shortli', 'never', 'quit', 'made', 'm...",gym shortli never quit made mile today mile wo...,...,0.000000,0.000000,0.347752,0.000000,0.000000,0.000000,1003,15,62.687500,1.363636

In [16]:
save_to_csv(user_tweets_feature_engineer, 'user_tweets_final_numeric_feature_engineer.csv', PROCESSED_DATA_DIR)

In [17]:
drop_lst = ['tweets_content', 'tweet_tokenized', 'tweet_tokenized_stem',
            'tweet_tokenized_lemma', 'tweet_tokenized_filtered', 'tweet_clean']
save_to_csv(user_tweets_feature_engineer.drop(columns=drop_lst),
            'user_tweets_only_numeric_feature_engineer.csv', PROCESSED_DATA_DIR)

# Save partial data for data exploration analysis

In [18]:
# eda_lst = ['followers_count', 'following_count', 'tweet_clean', 'state_back']
# eda_lst += ['count_word', 'tweets_count', 'count_sentence']
# eda_lst += ['count_reweet', 'count_mention', 'count_hashtag', 'count_url']
# eda_lst += ['reweet_per_word', 'mention_per_word', 'hashtag_per_word', 'url_per_word']
# eda_lst += ['reweet_per_sentence', 'mention_per_sentence', 'hashtag_per_sentence', 'url_per_sentence']
# eda_lst += ['reweet_per_tweet', 'mention_per_tweet', 'hashtag_per_tweet', 'url_per_tweet']
# eda_lst += ['word_per_sentence', 'word_per_tweet', 'sentence_per_tweet']

eda_lst = ['followers_count', 'following_count', 'tweet_clean', 'state_back']
# eda_lst += ['count_word', 'tweets_count', 'count_sentence']
# eda_lst += ['count_mention']
# eda_lst += ['mention_per_word']
# eda_lst += ['mention_per_sentence']
# eda_lst += ['mention_per_tweet']
eda_lst += ['word_per_sentence', 'sentence_per_tweet']


user_tweets_eda = user_tweets_feature_engineer[eda_lst]
user_tweets_eda

,followers_count,following_count,tweet_clean,state_back,word_per_sentence,sentence_per_tweet
0,379.0,383.0,rt cuban cyclist arleni sierra first place fir...,1,167.487805,0.869565
1,224.0,253.0,celia sánchez occupi signific place histori cu...,1,223.600000,0.571429
2,535.0,1144.0,worri everith ok vscode best editor ani backen...,1,97.080193,1.122997
3,827.0,740.0,rt state terror openli declar venezuela defeat...,1,121.695876,1.162651
4,43.0,304.0,rt patient ill covid precaut must heighten peo...,1,43.000000,1.000000
...,...,...,...,...,...,...
106592,5.0,16.0,check checkin hope get room earli need sleep m...,0,65.647059,1.454545
106593,43.0,38.0,swap meet wa fun today summer time even though...,0,78.233173,1.206395
106594,4.0,84.0,oh well complain want aboutt school want alrea...,0,58.337500,1.519231
106595,0.0,14.0,ate mani carrot tri knockout thi last paper fa...,0,179.000000,0.000000
106596,2.0,24.0,gym shortli never quit made mile today mile wo...,0,62.687500,1.363636

In [19]:
save_to_csv(user_tweets_eda, 'user_tweets_eda.csv', PROCESSED_DATA_DIR)
save_to_csv(user_tweets_eda.sample(n=1000, replace=False, axis=0), 'user_tweets_eda_1000.csv', PROCESSED_DATA_DIR)
save_to_csv(user_tweets_eda.sample(n=10000, replace=False, axis=0), 'user_tweets_eda_10000.csv', PROCESSED_DATA_DIR)