In [1]:
import os
import sys
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.utils import shuffle
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
sys.path.append(r'D:\OneDrive\Programming\documents_python\NUS Courses\DBA5106\Course-DBA5106\group_project\gp3')
from utils.logger import logger
from utils.config import RAW_DATA_DIR, PROCESSED_DATA_DIR, FIGURE_DIR
from utils.data_porter import save_to_csv, read_from_csv

In [3]:
user_tweets = read_from_csv('user_tweets_only_numeric_feature_engineer.csv', PROCESSED_DATA_DIR)

In [4]:
user_tweets

,followers_count,following_count,tweets_count,state_back,abl,actual,ago,aleksandar,almost,alreadi,...,yay,ye,yeah,year,yesterday,yet,count_word,count_sentence,word_per_sentence,sentence_per_tweet
0,379.0,383.0,45.0,1,0.071711,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.049154,0.000000,0.060629,6867,40,167.487805,0.869565
1,224.0,253.0,6.0,1,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1118,4,223.600000,0.571429
2,535.0,1144.0,9048.0,1,0.011755,0.005757,0.009084,0.0,0.011596,0.015488,...,0.002049,0.008471,0.002790,0.043911,0.012778,0.011926,986626,10162,97.080193,1.122997
3,827.0,740.0,165.0,1,0.055341,0.024641,0.053459,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.151733,0.025067,0.023394,23609,193,121.695876,1.162651
4,43.0,304.0,1.0,1,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129,2,43.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106592,5.0,16.0,10.0,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.053328,0.000000,0.096813,0.000000,0.055420,0.103444,1116,16,65.647059,1.454545
106593,43.0,38.0,343.0,0,0.000000,0.000000,0.000000,0.0,0.113056,0.198191,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32545,415,78.233173,1.206395
106594,4.0,84.0,51.0,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.096335,0.089906,4667,79,58.337500,1.519231
106595,0.0,14.0,2.0,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,179,0,179.000000,0.000000
106596,2.0,24.0,10.0,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.347752,0.000000,0.000000,0.000000,1003,15,62.687500,1.363636

In [5]:
user_tweets = shuffle(user_tweets, random_state=0)

In [6]:
y = user_tweets['state_back']
X = user_tweets.drop(columns=['state_back'])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [8]:
X_train

,followers_count,following_count,tweets_count,abl,actual,ago,aleksandar,almost,alreadi,also,...,yay,ye,yeah,year,yesterday,yet,count_word,count_sentence,word_per_sentence,sentence_per_tweet
103380,1.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0000,0.0,453,14,30.200000,2.000000
42824,30.0,27.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0000,0.0,356,5,59.333333,1.250000
39981,337.0,132.0,272.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0000,0.0,27524,363,75.615385,1.329670
5153,2.0,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0000,0.0,209,3,52.250000,0.750000
87696,6.0,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.199842,0.0,0.0,0.2261,0.0,318,2,106.000000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104616,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0000,0.0,344,7,43.000000,1.750000
75113,448.0,76.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0000,0.0,121,0,121.000000,0.000000
66939,10.0,19.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0000,0.0,315,4,63.000000,1.333333
70430,1551.0,3027.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.175894,...,0.0,0.000000,0.0,0.0,0.0000,0.0,1043,5,173.833333,0.625000
51028,249.0,363.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0000,0.0,186,2,62.000000,0.666667

In [9]:
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)
clf_probs = clf.predict_proba(X_test)

In [10]:
pred = clf.predict(X_test)
pred_train = clf.predict(X_train)

In [11]:
def matrix(y_test, pred):
    print('F1 Score on Test Set: {}'.format(metrics.f1_score(np.array(y_test), pred)))
    print('F1 Score on Training Set: {}'.format(metrics.f1_score(np.array(y_train), pred_train)))
    print('Recall Score on Test Set: {}'.format(metrics.recall_score(np.array(y_test), pred)))
    print('Recall Score on Training Set: {}'.format(metrics.recall_score(np.array(y_train), pred_train)))
    print('Precision Score on Test Set: {}'.format(metrics.precision_score(np.array(y_test), pred)))
    print('Precision Score on Training Set: {}'.format(metrics.precision_score(np.array(y_train), pred_train)))
matrix(y_test, pred)

F1 Score on Test Set: 0.9433085501858736
F1 Score on Training Set: 0.9997301021350341
Recall Score on Test Set: 0.9213661636219221
Recall Score on Training Set: 0.9995455191024002
Precision Score on Test Set: 0.9663215518267285
Precision Score on Training Set: 0.9999147533530348